---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: check
  image: golang:1.11
  commands:
  - make fmt-check

- name: docker-check
  image: plugins/docker
  settings:
    repo: techknowlogick/shiori
    dry_run: true

- name: build-node
  image: golang:1.11
  commands:
  - npm install
  - npx parcel build src/*.html --public-url /dist/

- name: build-go
  image: golang:1.11
  commands:
  - get -u github.com/gobuffalo/packr/v2/packr2
  - packr2 build

- name: cross
  image: golang:1.11
  commands:
  - gox -os="linux darwin windows" -arch="amd64 386" -output="dist/shiori.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...