---
kind: pipeline
name: default


workspace:
  base: /go
  path: src/src.techknowlogick.com/shiori

platform:
  os: linux
  arch: amd64

steps:
- name: check
  image: golang:1.12
  commands:
  - make fmt-check

- name: docker-check
  image: plugins/docker
  settings:
    repo: techknowlogick/shiori
    dry_run: true
  when:
    event:
    - pull_request

- name: build-node
  image: node:10
  commands:
  - make dep-node

- name: build-go
  image: golang:1.12
  environment:
    GO111MODULE: on
  commands:
  - GO111MODULE=auto go get -u github.com/gobuffalo/packr/v2/packr2
  - go mod download
  - packr2
  - make build
  - ./shiori
  - ./shiori add https://example.com
  - ./shiori print
  - ./shiori delete 1
  - ./shiori add https://src.techknowlogick.com
  - ./shiori add https://www.thestar.com/news/gta/2019/02/13/woman-accused-of-throwing-a-chair-off-downtown-toronto-balcony-turns-herself-in.html
  - ./shiori print

- name: docker-publish-nightly
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: techknowlogick/shiori
    tags: latest, nightly
  when:
    event: push
    branch: master
 
- name: docker-publish-tag
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: techknowlogick/shiori
    auto_tag: true
    default_tags: true
  when:
    event: tag

- name: cross
  image: techknowlogick/xgo
  commands:
  - make cross
  when:
    event:
      exclude:
        - pull_request

- name: compress-and-checksum
  image: golang:1.12
  commands:
  - make release
  when:
    event:
      exclude:
        - pull_request

- name: release-nightly
  image: plugins/s3
  settings:
    bucket: uploads
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    acl: download
    endpoint: https://storage.techknowlogick.com
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /shiori/nightly
  when:
    event:
    - push
    branch:
    - master

- name: release-tag
  image: plugins/s3
  settings:
    bucket: uploads
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    acl: download
    endpoint: https://storage.techknowlogick.com
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /shiori/${DRONE_TAG##v}
  when:
    event: tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: dist/release/*
  when:
    event: tag
