---
kind: pipeline
name: default


workspace:
  base: /go
  path: src/src.techknowlogick.com/shiori

platform:
  os: linux
  arch: amd64

steps:
- name: check
  image: golang:1.13
  commands:
  - make fmt-check

- name: docker-check
  image: plugins/docker
  settings:
    repo: techknowlogick/shiori
    dry_run: true
  when:
    event:
    - pull_request

- name: build-node
  image: node:10
  commands:
  - make dep-node

- name: build-go
  image: golang:1.13
  environment:
    GO111MODULE: on
  commands:
  - GO111MODULE=off go get -u github.com/markbates/pkger/cmd/pkger
  - go mod download
  - pkger
  - make build
  - ./shiori
  - ./shiori add https://example.com
  - ./shiori print
  - ./shiori delete 1
  - ./shiori add https://src.techknowlogick.com
  - ./shiori add https://www.thestar.com/news/gta/2019/02/13/woman-accused-of-throwing-a-chair-off-downtown-toronto-balcony-turns-herself-in.html
  - ./shiori print

- name: docker-publish-nightly
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: techknowlogick/shiori
    tags: latest, nightly
  when:
    event: push
    branch: master
 
- name: docker-publish-tag
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: techknowlogick/shiori
    auto_tag: true
    default_tags: true
  when:
    event: tag

- name: cross
  image: techknowlogick/xgo
  environment:
    GO111MODULE: on
  commands:
  - rm -rf /source
  - ln -s $CI_WORKSPACE /source
  - go get
  - make cross
  when:
    event:
      exclude:
        - pull_request

- name: compress-and-checksum
  image: golang:1.13
  commands:
  - make release
  when:
    event:
      exclude:
        - pull_request

- name: docs-check
  image: node:10
  commands:
  - make build-docs

- name: publish-documentation
  image: lucap/drone-netlify
  settings:
    path: ./_docpress
    token:
      from_secret: netlify_token
    site_id:
      from_secret: netlify_site_id
  when:
    event:
    - push
    branch:
    - master

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: dist/release/*
  when:
    event: tag
